@Batcher_HostAddress = http://localhost:7007

POST {{Batcher_HostAddress}}/batcher/batcher-trigger/
Content-Type: application/json
Accept: application/json


{
  "SourceFolderPath": "PDFs/",
  "destination_folder_path": "uploadedPDFs/",
  "SearchItemsFolderPath": "search_index_items/",
  "SearchIndexerName": "searchindexdemo"
}
